=== UO302109/SEW/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.uniovi.es"
           xmlns:uo="http://www.uniovi.es">

    <xs:simpleType name="tipoAltitud">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoDistancia">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1000000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoRecomendacion">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="rutas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:ruta" minOccurs="3" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ruta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:nombre"/>
                <xs:element ref="uo:tipo"/>
                <xs:element ref="uo:medioTransporte"/>
                <xs:element ref="uo:fechaInicio" minOccurs="0"/>
                <xs:element ref="uo:horaInicio" minOccurs="0"/>
                <xs:element ref="uo:duracion"/>
                <xs:element ref="uo:agencia"/>
                <xs:element ref="uo:descripcion"/>
                <xs:element ref="uo:personasAdecuadas"/>
                <xs:element ref="uo:lugarInicio"/>
                <xs:element ref="uo:direccionInicio"/>
                <xs:element ref="uo:coordenadasInicio"/>
                <xs:element ref="uo:bibliografia"/>
                <xs:element ref="uo:recomendacion"/>
                <xs:element ref="uo:hitos"/>
                <xs:element ref="uo:planimetria"/>
                <xs:element ref="uo:altimetria"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="tipo" type="xs:string"/>
    <xs:element name="medioTransporte" type="xs:string"/>
    <xs:element name="fechaInicio" type="xs:date"/>
    <xs:element name="horaInicio" type="xs:time"/>
    <xs:element name="duracion" type="xs:string"/>
    <xs:element name="agencia" type="xs:string"/>
    <xs:element name="descripcion" type="xs:string"/>
    <xs:element name="personasAdecuadas" type="xs:string"/>
    <xs:element name="lugarInicio" type="xs:string"/>
    <xs:element name="direccionInicio" type="xs:string"/>
    <xs:element name="recomendacion" type="uo:tipoRecomendacion"/>

    <xs:element name="coordenadasInicio">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:long"/>
                <xs:element ref="uo:lat"/>
                <xs:element ref="uo:altitud"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="coordenadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:long"/>
                <xs:element ref="uo:lat"/>
                <xs:element ref="uo:altitud"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="long">
        <xs:simpleType>
            <xs:restriction base="xs:float">
                <xs:minInclusive value="-180"/>
                <xs:maxInclusive value="180"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="lat">
        <xs:simpleType>
            <xs:restriction base="xs:float">
                <xs:minInclusive value="-90"/>
                <xs:maxInclusive value="90"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="altitud">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="uo:tipoAltitud">
                    <xs:attribute name="unidad" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="bibliografia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:referencia" minOccurs="3" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="referencia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="alt" type="xs:string" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="hitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:hito" minOccurs="5" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="hito">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:nombre" minOccurs="0"/>
                <xs:element ref="uo:descripcion" minOccurs="0"/>
                <xs:element ref="uo:coordenadas"/>
                <xs:element ref="uo:distanciaAnterior"/>
                <xs:element ref="uo:galeriaFotos" minOccurs="0"/>
                <xs:element ref="uo:galeriaVideos" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="distanciaAnterior">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="uo:tipoDistancia">
                    <xs:attribute name="unidad" type="xs:string" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="galeriaFotos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:imagen" minOccurs="1" maxOccurs="5"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="galeriaVideos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="uo:video" minOccurs="1" maxOccurs="3"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="imagen">
        <xs:complexType>
            <xs:attribute name="urlf" type="xs:string" use="required"/>
            <xs:attribute name="alt" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="video">
        <xs:complexType>
            <xs:attribute name="urlv" type="xs:string" use="required"/>
            <xs:attribute name="alt" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="planimetria" type="xs:string"/>
    <xs:element name="altimetria" type="xs:string"/>

</xs:schema>

=== UO302109/SEW/xml/rutas.xml
<?xml version='1.0' encoding='UTF-8'?>
<rutas xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es rutas.xsd">

    <ruta>
        <nombre>Casco histórico de Burgos</nombre>
        <tipo>Arquitectura y monumentos</tipo>
        <medioTransporte>A pie</medioTransporte>
        <fechaInicio>2026-04-12</fechaInicio>
        <horaInicio>10:00:00</horaInicio>
        <duracion>4 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Recorrido a pie por el conjunto monumental de la ciudad de Burgos, declarada Patrimonio de la Humanidad. Partiendo del Museo de la Evolución Humana, la ruta sigue el Paseo del Espolón, cruza el Arco de Santa María y termina en la Catedral, recorriendo más de mil años de historia castellana.</descripcion>
        <personasAdecuadas>Apta para todos los públicos, incluidas familias con niños</personasAdecuadas>
        <lugarInicio>Museo de la Evolución Humana</lugarInicio>
        <direccionInicio>Paseo Sierra de Atapuerca, s/n - 09002 Burgos</direccionInicio>
        <coordenadasInicio>
            <long>-3.697144</long>
            <lat>42.339372</lat>
            <altitud unidad="metros">858</altitud>
        </coordenadasInicio>
        <bibliografia>
            <referencia alt="Turismo de Burgos">https://www.turismoburgos.org/</referencia>
            <referencia alt="Catedral de Burgos en Wikipedia">https://es.wikipedia.org/wiki/Catedral_de_Burgos</referencia>
            <referencia alt="Museo de la Evolución Humana">https://www.museoevolucionhumana.com/</referencia>
        </bibliografia>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito>
                <nombre>Museo de la Evolución Humana</nombre>
                <descripcion>Museo dedicado a la evolución humana y a los hallazgos paleontológicos de los yacimientos de la Sierra de Atapuerca, Patrimonio de la Humanidad. Diseñado por Juan Navarro Baldeweg, es una de las visitas imprescindibles de Burgos.</descripcion>
                <coordenadas>
                    <long>-3.697144</long>
                    <lat>42.339372</lat>
                    <altitud unidad="metros">858</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">0</distanciaAnterior>
                <galeriaFotos>
                    <imagen urlf="../multimedia/meh_exterior.jpg" alt="Edificio del Museo de la Evolución Humana"/>
                    <imagen urlf="../multimedia/meh_interior.jpg" alt="Sala de exposiciones del museo"/>
                </galeriaFotos>
                <galeriaVideos>
                    <video urlv="../multimedia/meh_recorrido.mp4" alt="Recorrido por el museo"/>
                </galeriaVideos>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.697374</long>
                    <lat>42.339991</lat>
                    <altitud unidad="metros">859</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">71</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.699039</long>
                    <lat>42.339727</lat>
                    <altitud unidad="metros">856</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">140</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.699584</long>
                    <lat>42.340699</lat>
                    <altitud unidad="metros">862</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">117</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.699728</long>
                    <lat>42.340439</lat>
                    <altitud unidad="metros">862</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">31</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.701919</long>
                    <lat>42.339907</lat>
                    <altitud unidad="metros">862</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">189</distanciaAnterior>
            </hito>
            <hito>
                <nombre>Paseo del Espolón</nombre>
                <descripcion>Paseo arbolado a orillas del río Arlanzón, corazón de la vida social burgalesa desde el siglo XVIII. Sus plátanos centenarios y el famoso quiosco de música lo convierten en uno de los lugares más emblemáticos de la ciudad.</descripcion>
                <coordenadas>
                    <long>-3.701979</long>
                    <lat>42.340151</lat>
                    <altitud unidad="metros">868</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">28</distanciaAnterior>
                <galeriaFotos>
                    <imagen urlf="../multimedia/espolon.jpg" alt="Paseo del Espolón con sus plátanos centenarios"/>
                </galeriaFotos>
            </hito>
            <hito>
                <nombre>Arco de Santa María</nombre>
                <descripcion>Antigua puerta de la muralla medieval y entrada monumental al casco histórico de Burgos. Reconstruida en el siglo XVI a modo de retablo en honor al emperador Carlos V, alberga en su interior una sala de exposiciones.</descripcion>
                <coordenadas>
                    <long>-3.703819</long>
                    <lat>42.339765</lat>
                    <altitud unidad="metros">864</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">157</distanciaAnterior>
                <galeriaFotos>
                    <imagen urlf="../multimedia/arco_santamaria.jpg" alt="Arco de Santa María iluminado"/>
                </galeriaFotos>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.704216</long>
                    <lat>42.340002</lat>
                    <altitud unidad="metros">874</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">42</distanciaAnterior>
            </hito>
            <hito>
                <nombre>Plaza del Rey San Fernando</nombre>
                <descripcion>Plaza monumental en el corazón del casco histórico, situada frente a la fachada principal de la Catedral. Recibe su nombre en honor a Fernando III el Santo, rey castellano que ordenó iniciar la construcción de la Catedral en 1221.</descripcion>
                <coordenadas>
                    <long>-3.703939</long>
                    <lat>42.340349</lat>
                    <altitud unidad="metros">870</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">45</distanciaAnterior>
                <galeriaFotos>
                    <imagen urlf="../multimedia/plaza_rey_fernando.jpg" alt="Plaza del Rey San Fernando con la Catedral al fondo"/>
                </galeriaFotos>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.704875</long>
                    <lat>42.339936</lat>
                    <altitud unidad="metros">863</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">90</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.705562</long>
                    <lat>42.339749</lat>
                    <altitud unidad="metros">871</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">60</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.705866</long>
                    <lat>42.339794</lat>
                    <altitud unidad="metros">872</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">25</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.705639</long>
                    <lat>42.339971</lat>
                    <altitud unidad="metros">871</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">27</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.705230</long>
                    <lat>42.340095</lat>
                    <altitud unidad="metros">882</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">36</distanciaAnterior>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.705367</long>
                    <lat>42.340204</lat>
                    <altitud unidad="metros">882</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">17</distanciaAnterior>
            </hito>
            <hito>
                <nombre>Iglesia de San Nicolás de Bari</nombre>
                <descripcion>Templo gótico del siglo XV famoso por su impresionante retablo mayor de piedra policromada, una de las obras maestras del gótico hispano. Situada en la calle Fernán González, junto a la Catedral.</descripcion>
                <coordenadas>
                    <long>-3.705511</long>
                    <lat>42.340544</lat>
                    <altitud unidad="metros">882</altitud>
                </coordenadas>
                <distanciaAnterior unidad="metros">40</distanciaAnterior>
                <galeriaFotos>
                    <imagen urlf="../multimedia/sannicolas.jpg" alt="Retablo de la iglesia de San Nicolás"/>
                </galeriaFotos>
            </hito>
            <hito>
                <coordenadas>
                    <long>-3.705414</long>
                    <lat>42.340573</lat>
